name: Линтер кода, Тестирование, Сборка
run-name: ${{ github.actor }} тестирует Github Actions
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    runs-on: [ windows-2019 ]
    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Установка Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Установка зависимостей
        run: npm install

      - name: Продакшен сборка проекта webpack
        run: npm run build:prod

      - name: Продакшен сборка проекта vite
        run: npm run build:prod:vite

      - name: Линтер Typescript
        if: always()
        run: npm run lint:ts

      - name: Линтер CSS|SCSS
        if: always()
        run: npm run lint:scss

      - name: Unit-тестирование
        if: always()
        run: npm run test:unit

      - name: Сборка Storybook
        run: npm run storybook:build

      - name: Регрессионное тестирование (Скриншотное тестирование)
        if: always()
        run: npm run test:ui:ci